{% set version = "4.0" %}

package:
  name: python-libarchive-c
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/l/libarchive-c/libarchive-c-{{ version }}.tar.gz
    sha256: a5b41ade94ba58b198d778e68000f6b7de41da768de7140c984f71d7fa8416e5
    patches:
      # TODO: follow up with upstream https://github.com/Changaco/python-libarchive-c/pull/120
      - 0000-read-with-utf8.patch
build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - libarchive
    - python

test:
  source_files:
    - tests  # [unix]
    - README.rst
  files:
    - test/hello_world.xar
  imports:
    - libarchive
  requires:
    - mock
    - pytest-cov
  commands:
    - python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"  # [not win]
    - python -c "import libarchive; libarchive.extract_file('test\\hello_world.xar')"  # [win]
    - python -c "import os, shutil, libarchive; shutil.copytree(os.path.dirname(libarchive.__file__), 'libarchive')"  # [unix]
    - pytest -vv --cov libarchive --cov-report term-missing:skip-covered --cov-fail-under=85  # [linux]
    - pytest -vv --cov libarchive -k "not (test_fd or test_files or test_buffers or atime_ctime or custom_writer)"  # [osx]

about:
  home: https://github.com/Changaco/python-libarchive-c
  license: CC0-1.0
  license_family: CC
  summary: Python interface to libarchive
  license_file: cc0-1.0.txt


extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
    - ocefpaf
