{% set version = "3.2" %}

package:
  name: python-libarchive-c
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/l/libarchive-c/libarchive-c-{{ version }}.tar.gz
    sha256: 21ad493f4628972fc82440bff54c834a9fbe13be3893037a4bad332b9ee741e5
  - folder: src
    url: https://github.com/Changaco/python-libarchive-c/archive/refs/tags/{{ version }}.tar.gz
    sha256: e09bd195f72646472f7514145f8f65fd371444d9c98123cd6ec7555048d57045

build:
  number: 0
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - libarchive
    - python

test:
  source_files:
    - src/tests  # [unix]
    - src/README.rst
  files:
    - test/hello_world.xar
  imports:
    - libarchive
  requires:
    - mock
    - pytest-cov
  commands:
    - python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"  # [not win]
    - python -c "import libarchive; libarchive.extract_file('test\\hello_world.xar')"  # [win]
    - python -c "import os, shutil, libarchive; shutil.copytree(os.path.dirname(libarchive.__file__), 'src/libarchive')"  # [unix]
    - cd src && pytest -vv --cov libarchive --cov-report term-missing:skip-covered --cov-fail-under=90  # [linux]
    - cd src && pytest -vv --cov libarchive -k "not (test_fd or test_files or test_buffers or atime_ctime or custom_writer)"  # [osx]

about:
  home: https://github.com/Changaco/python-libarchive-c
  license: CC0-1.0
  license_family: CC
  summary: Python interface to libarchive
  license_file: cc0-1.0.txt


extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
    - ocefpaf
