{% set pypi = "libarchive-c" %}
{% set name = "python-libarchive-c" %}
{% set version = "2.8" %}
{% set sha256 = "06d44d5b9520bdac93048c72b7ed66d11a6626da16d2086f9aad079674d8e061" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi[0] }}/{{ pypi }}/{{ pypi }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Add-zstd-support.patch

build:
  number: 1003
  script:
  - set PYTHONHASHSEED=0  # [win]
  - export PYTHONHASHSEED=0  # [not win]
  - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --progress-bar off -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - libarchive
    - python

test:
  files:
    - test/hello_world.xar
  imports:
    - libarchive
  commands:
    - python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"  # [not win]
    - python -c "import libarchive; libarchive.extract_file('test\\hello_world.xar')"  # [win]

about:
  home: https://github.com/Changaco/python-libarchive-c
  license: CC0-1.0
  summary: Python interface to libarchive

extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
    - ocefpaf
