{% set version = "3.1" %}

package:
  name: python-libarchive-c
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/l/libarchive-c/libarchive-c-{{ version }}.tar.gz
    sha256: 618a7ecfbfb58ca15e11e3138d4a636498da3b6bc212811af158298530fbb87e
  - folder: src
    url: https://github.com/Changaco/python-libarchive-c/archive/refs/tags/{{ version }}.tar.gz
    sha256: bef034fbc403feacc4d28e71520eff6a1fcc4a677f0bec5324f68ea084c8c103

build:
  number: 0
  script:
    - cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - libarchive
    - python

test:
  source_files:
    - src/tests  # [unix]
    - src/README.rst
  files:
    - test/hello_world.xar
  imports:
    - libarchive
  requires:
    - mock
    - pytest-cov
  commands:
    - python -c "import libarchive; libarchive.extract_file('test/hello_world.xar')"  # [not win]
    - python -c "import libarchive; libarchive.extract_file('test\\hello_world.xar')"  # [win]
    - python -c "import os, shutil, libarchive; shutil.copytree(os.path.dirname(libarchive.__file__), 'src/libarchive')"  # [unix]
    - cd src && pytest -vv --cov libarchive --cov-report term-missing:skip-covered --cov-fail-under=90  # [linux]
    - cd src && pytest -vv --cov libarchive -k "not (test_fd or test_files or test_buffers or atime_ctime)"  # [osx]

about:
  home: https://github.com/Changaco/python-libarchive-c
  license: CC0-1.0
  license_family: CC
  summary: Python interface to libarchive
  license_file: cc0-1.0.txt


extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
    - ocefpaf
