# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 5.2

package:
  name: python-libarchive-c
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/libarchive-c/libarchive_c-${{ version }}.tar.gz
  sha256: fd44a8e28509af6e78262c98d1a54f306eabd2963dfee57bf298977de5057417

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    # https://github.com/conda-forge/python-libarchive-c-feedstock/issues/35
    - ${{ PYTHON }} ${{ RECIPE_DIR }}/delete_unicode_files.py

requirements:
  host:
    - pip
    - setuptools
    - python ${{ pythnon_min }}.*
  run:
    - libarchive
    - python >=${{ python_min }}

tests:
  - python:
      imports: libarchive
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      recipe:
        - test/
        - run_test.py
      source:
        - README.rst
        - tests/
    requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    script:
      - python run_test.py

about:
  license: CC0-1.0
  summary: Python interface to libarchive
  license_file:
    - cc0-1.0.txt
    - LICENSE.md
  homepage: https://github.com/Changaco/python-libarchive-c

extra:
  recipe-maintainers:
    - bollwyvl
    - mingwandroid
    - ocefpaf
